server:
  port: 8086

spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

    loadbalancer:
      ribbon:
        enabled: false # 禁用 Ribbon 的负载均衡
      rules:
        - com.netflix.loadbalancer.RandomRule

  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2003098



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
